drop table if exists user_groups cascade;
drop table if exists groups cascade;
drop table if exists users cascade;

create table if not exists groups
(
    group_id    bigint       not null primary key GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) not null,
    description varchar(255) not null
);

create table if not exists users
(
    user_id    bigint       not null primary key GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(255) not null,
    last_name  varchar(255) not null
);

create table if not exists user_groups
(
    user_id  bigint not null,
    group_id bigint not null,
    constraint user_groups_PK primary key (user_id, group_id),
    constraint user_groups_FK1 foreign key (user_id) references users (user_id),
    constraint user_groups_FK2 foreign key (group_id) references groups (group_id)
);
