package jdbc.config;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DataSource {

    private static final String POSTRESQL_URL = "jdbc:postgresql://localhost:5432/aston";
    private static final String USER = "user";
    private static final String PASSWORD = "password";


    private DataSource() {
        throw new RuntimeException();
    }

    public static Connection getConnection() {
        try {
            Class.forName("org.postgresql.Driver");
            return DriverManager.getConnection(POSTRESQL_URL, USER, PASSWORD);
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

    public static void initDataBase() {
        try (Connection connection = getConnection()) {
            String sql = """
                    drop table if exists user_groups cascade;
                    drop table if exists groups cascade;
                    drop table if exists users cascade;
                                                          
                    create table if not exists groups (
                     group_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY,
                    name varchar(255) not null,
                    description varchar(255) not null
                    );
                                                           
                    insert into groups (name, description) values ('group1','group1desc1');
                    insert into groups (name, description) values ('group2','group2desc2');
                                     \s
                    create table if not exists users (
                    	user_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY,
                    	first_name varchar(255) not null,
                    	second_name varchar(255) not null
                    );

                    insert into users (first_name, second_name) values ('emma','hill');
                    insert into users (first_name, second_name) values ('tom','anderson');


                    create table if not exists user_groups (
                    	user_id bigint not null,
                    	group_id bigint not null,
                    	constraint user_groups_PK primary key (user_id, group_id),
                    	constraint user_groups_FK1 foreign key (user_id) references users (user_id) on delete cascade on update restrict,
                    	constraint user_groups_FK2 foreign key (group_id) references groups (group_id) on delete cascade on update restrict
                    );


                    insert into user_groups (user_id, group_id) values (1,1);
                    insert into user_groups (user_id, group_id) values (1,2);
                    insert into user_groups (user_id, group_id) values (2,2);
                                        """;
            Statement statement = connection.createStatement();
            statement.execute(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
