package jdbc.dao;

import jdbc.dto.UserRequestDto;
import jdbc.model.User;

import java.sql.*;
import java.util.*;

public class UserDaoImpl implements UserDao {

    private static final String URL = "jdbc:postgresql://localhost:5432/aston";
    private static final String USER = "user";
    private static final String PASSWORD = "password";

    public UserDaoImpl() {
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = """
                    drop table if exists users cascade;
                                        
                    create table if not exists users (
                    	user_id bigint not null primary key GENERATED BY DEFAULT AS IDENTITY,
                    	first_name varchar(255) not null,
                    	second_name varchar(255) not null
                    );
                    """;
            Statement statement = connection.createStatement();
            statement.execute(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<User> getUsers() {
        List<User> users = new LinkedList<>();
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
            Statement statement = connection.createStatement();
            String sql = "select * from users order by user_id asc;";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                int id = resultSet.getInt(1);
                String firstName = resultSet.getString(2);
                String secondName = resultSet.getString(3);
                users.add(User.builder()
                        .userId(id)
                        .firstName(firstName)
                        .secondName(secondName).build());
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return Collections.emptyList();
        }
        return users;
    }

    @Override
    public Optional<User> getUserById(Integer userId) {
        User user = null;
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "select * from users where user_id = ?;";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, userId);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                user = User.builder()
                        .userId(userId)
                        .firstName(resultSet.getString("first_name"))
                        .secondName(resultSet.getString("second_name"))
                        .build();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return Optional.empty();
        }
        return user != null ? Optional.of(user) : Optional.empty();
    }

    @Override
    public Optional<User> createUser(UserRequestDto userRequestDto) {
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "INSERT INTO users (first_name, second_name) VALUES (?, ?);";
            PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            preparedStatement.setString(1, userRequestDto.firstName());
            preparedStatement.setString(2, userRequestDto.secondName());
            preparedStatement.executeUpdate();
            ResultSet resultSet = preparedStatement.getGeneratedKeys();
            int id = resultSet.getInt(1);
            return getUserById(id);
        } catch (SQLException e) {
            e.printStackTrace();
            return Optional.empty();
        }
    }

    @Override
    public Optional<User> updateUser(Integer userId, UserRequestDto userRequestDto) {
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "update users set first_name = ?, second_name = ? where user_id = ?;";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, userRequestDto.firstName());
            preparedStatement.setString(2, userRequestDto.secondName());
            preparedStatement.setInt(3, userId);
            preparedStatement.executeUpdate();
            return getUserById(userId);
        } catch (SQLException e) {
            e.printStackTrace();
            return Optional.empty();
        }
    }

    @Override
    public boolean deleteUser(Integer userId) {
        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "delete from users where user_id = ?;";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, userId);
            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
}
